'use strict'

export const NIGERIAN_STATES = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT (Abuja)',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
]

export const SOCIAL_PLATFORMS = {
  linkedin: { name: 'LinkedIn', icon: 'FaLinkedin', color: '#0A66C2' },
  github: { name: 'GitHub', icon: 'FaGithub', color: '#181717' },
  x: { name: 'X (Twitter)', icon: 'FaXTwitter', color: '#000000' },
  instagram: { name: 'Instagram', icon: 'FaInstagram', color: '#E4405F' },
  facebook: { name: 'Facebook', icon: 'FaFacebook', color: '#1877F2' },
  dribbble: { name: 'Dribbble', icon: 'FaDribbble', color: '#EA4C89' },
  behance: { name: 'Behance', icon: 'FaBehance', color: '#1769FF' },
  whatsapp: { name: 'WhatsApp', icon: 'FaWhatsapp', color: '#25D366' },
  youtube: { name: 'YouTube', icon: 'FaYoutube', color: '#FF0000' },
  tiktok: { name: 'TikTok', icon: 'FaTiktok', color: '#000000' },
  global: { name: 'Global', icon: 'FaGlobe', color: '#6B73FF' },
  medium: { name: 'Medium', icon: 'FaMedium', color: '#000000' },
  stackoverflow: { name: 'Stack Overflow', icon: 'FaStackOverflow', color: '#F58025' },
  figma: { name: 'Figma', icon: 'FaFigma', color: '#F24E1E' },
}